services:
  backend:
    build: backend
    secrets:
      - db-password
    depends_on:
      - db
  foreend:
    build: foreend
  db:
    image: progresql:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecrect
      expose:
      - 5432
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
