version: "3.7"
services:
  backend:
    build:
      context: backend
      target: development
    secrets:
      - db-password
    depends_on:
      - db
  foreend:
    build: 
      context: foreend
      target: development
  db:
    image: progresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD=mysecrect
    expose:
      - 5432
  proxy:
    build: proxy
    ports:
      - 8080:80
    depends_on:
      - backend
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
